srce/django_blog/urls.py
from django.conf.urls.static import static
from django_blog import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

srce/posts/urls.py
from django.urls import path
from posts.views import HomeBlog, BlogPostCreate, BlogPostUpdate, BlogPostDetail, BlogPostDelete

app_name = 'posts'
urlpatterns = [
    path('', HomeBlog.as_view(), name='home'),
    path('create/', BlogPostCreate.as_view(), name='create'),
    path('<str:slug>/', BlogPostDetail.as_view(), name='detail'),
    path('edite/<str:slug>/', BlogPostUpdate.as_view(), name='edite'),
    path('delete/<str:slug>/', BlogPostDelete.as_view(), name='delete'),
]

srce/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
#model utilisateur de base de django
user = get_user_model()
# Create your models here.

class BlogPost(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name='titre')
    slug = models.SlugField(max_length=255, unique=True,blank=True)
    author = models.ForeignKey(user, on_delete=models.SET_NULL, null=True, blank=True)
    #enregistre avec la date actuel automatiquement
    last_update = models.DateTimeField(auto_now=True)
    created_on = models.DateField(blank=True, null=True)
    published = models.BooleanField(default=False, verbose_name='publié')
    content = models.TextField(blank=True, verbose_name='contenu')
    image = models.ImageField(blank=True, upload_to='blog')

    class Meta:
        #ordoner inversement de created_on
        ordering = ['-created_on']
        verbose_name = 'article'

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def author_or_default(self):
        if self.author:
            return self.author.username
        return "L'auteur inconnu"

#redirection absolue
    def get_absolute_url(self):
        return reverse('posts:home')

srce/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from posts.models import BlogPost
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
# Create your views here.

class HomeBlog(ListView):
    model = BlogPost
    context_object_name = 'posts'

#effectuer des verification
    def get_queryset(self):
        queryset = super().get_queryset()
        #si l'utilisateur est connecter
        if self.request.user.is_authenticated:
            return queryset
        return queryset.filter(published=True)

@method_decorator(login_required, name='dispatch' )
class BlogPostCreate(CreateView):
    model = BlogPost
    template_name = 'posts/blogpost_create.html'
    fields = ['title', 'content']

class BlogPostUpdate(UpdateView):
    model = BlogPost
    template_name = 'posts/blogpost_edite.html'
    fields = ['title', 'content', 'published']

class BlogPostDetail(DetailView):
    model = BlogPost
    context_object_name = 'post'

class BlogPostDelete(DeleteView):
    model = BlogPost
    template_name = 'posts/blogpost_confirm_delete.html'
    context_object_name = 'post'
    success_url = reverse_lazy('posts:home')

srce/posts/templates/posts/blogpost_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    <title>Supprimer</title>
{% endblock %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <h3>etes-vous sur de vouloir supprimer {{post.title}}</h3>
        <input type="submit" value="Oui, supprimer" class="btn btn-delete">
    </form>
{% endblock %}

srce/posts/templates/posts/blogpost_create.html
{% extends 'base.html' %}

{% block title %}
    <title> Ajouter un article </title>
{% endblock %}

{% block content %}
  <h1> Ajouter un article</h1>
    <form method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="cree" class="btn btn-submit">
    </form>
{% endblock %}

srce/posts/templates/posts/blogpost_detail.html
{% extends 'base.html' %}

{% block title %}
  <title>{{ post.title }}</title>
{% endblock %}

{% block content %}
    <article class="post-detail">
        <h1>{{ post.title }}</h1>
        <img src="{{post.image.url}}" alt="image">
        <div>{{ post.content|linebreaks|safe }}</div>
    </article>
{% endblock %}

srce/posts/templates/posts/blogpost_edite.html
{% extends 'base.html' %}

{% block title %}
    <title> Edité un article </title>
{% endblock %}

{% block content %}
  <h1> Edité un article</h1>
    <form method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="modifier" class="btn btn-submit">
    </form>
{% endblock %}

srce/posts/templates/posts/blogpost_list.html
{% extends 'base.html' %}

{% block title %}
  <title>Acceuil blog</title>
{% endblock %}

{% block content %}
  <h1> Le blog de Delmas</h1>
  {% for post in posts %}
      <article>
          <div class="post-title">
            <h2>{{ post.title }}</h2>
              {% if request.user.is_authenticated %}
                  <div>
                      <a href=" {% url 'posts:edite' slug=post.slug %}">Edité</a>
                      <a href=" {% url 'posts:delete' slug=post.slug %}">Supprimer</a>
                  </div>
              {% endif %}
          </div>
        <h5 class="post-author">publié par <i>{{post.author_or_default}}</i> le {{post.created_on|date:'j F y'}}</h5>
        <p class="post-excerpt">{{ post.content|safe|truncatewords:50}}</p>
          <form action="{% url 'posts:detail' slug=post.slug %}">
              <button class="btn btn-submit">Lire l'article</button>
          </form>
      </article>
  {% endfor %}
{% endblock %}

srce/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    {% block title%}
        <title>Acceil</title>
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
</head>
<body>
    <nav>
        <a href=" {% url 'posts:home' %}">Acceuil</a>
        {% if request.user.is_authenticated %}
            <a href=" {% url 'posts:create' %}">Ajouter un article</a>
        {% endif %}
    </nav>
    <section id="blog">
        {% block content %}
        {% endblock %}
    </section>
</body>
</html>